In [2]:
import numpy as np

# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [9]:
# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': np.shape(A),
    'B': np.shape(B),
    'C': np.shape(C),
    'D': np.shape(D),
    'u': (1,np.size(u)),
    'v': (1,np.size(v))
}

print(dimensions)

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (1, 4), 'v': (1, 4)}


In [20]:
# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = u+v            # u+v
u_minus_v = u-v           # u-v
alpha_times_u = alpha*u       # alpha * u, alpha = 6
u_dot_v = np.vdot(u,v)             # u . v
norm_u = np.linalg.norm(u)              # ||u||

8.602325267042627


In [32]:
# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None #np.mat(A)+np.mat(C)             # A + C
A_minus_Ctranspose = np.mat(A)-np.mat(C).getT()   # A - C.T
Ctranspose_plus_3D = np.mat(C).getT()+ 3*np.mat(D)   # C.T + 3*D
B_times_A = np.mat(B)*np.mat(A)            # B*A
B_times_Atranspose = None #np.mat(B)*np.mat(A).getT()   # B*A.T

In [42]:
# Q4: (bonus)

B_times_C = None #np.mat(B)*np.mat(C)            # B*C
C_times_B = np.mat(C)*np.mat(B)            # C*B
B_exp_4 = np.mat(B)*np.mat(B)*np.mat(B)*np.mat(B)     # B^4 #np.mat(B)^4 gives wrong result????
A_times_Atranspose = np.mat(A)*np.mat(A).getT()   # A*A.T
Dtranspose_times_D = np.mat(D).getT()*np.mat(D)   # D.T*D


[[10 -4  0]
 [-4  8  8]
 [ 0  8 10]]
